name: Bug Reports
description: Meld een bug waar de developers van moeten weten
title: "[Bug Report]: "
labels: ["bug", "new"]
body:
  - type: markdown
    attributes:
      value: |
        Dankjewel dat je deze bug wil melden!
        De onderstaande gegevens moet je zo goed en zo duidelijk mogelijk invullen zodat wij het sneller kunnen fixen!
  - type: input
    id: contact
    attributes:
      label: Contact
      description: Als wij inhoudelijk in moeten gaan op de bug, naar welke discord naam kunnen wij een bericht sturen?
      placeholder: bijv. Jeremy.#7020
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Wat is er gebeurd?
      description: Wat is er precies gebeurd, heb je errors gezien in je F8? Was er een crash?
      placeholder: |
        Voorbeeld: Ik zag dat er een error in de F8, dit gaf aan dat je geen spullen kon pakken uit de kluis van de politie.
    validations:
      required: true
  - type: textarea
    id: what-should-happen
    attributes:
      label: Wat moet er normaal gesproken te gebeuren?
      description: Wat hoorde er te gebeuren?
      placeholder: |
        Voorbeeld: Er moet wel spullen te pakken zijn uit de kluis, dit moet er gebeuren.
      validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: "Wat veroorzaakt de bug?"
      description: "Wat kunnen wij doen om ervoor te zorgen dat wij deze bug zelf kunnen meemaken?"
      placeholder: |
        Voorbeeld: Open de politie kluis, ga naar wapens, en probeer een wapen te pakken.
    validations:
      required: false
  - type: dropdown
    id: frequency
    attributes:
      description: "Hoevaak komt deze bug voor?"
      label: "Frequentie van de bug"
      options:
        - Altijd
        - Meerdere keren per dag
        - 1x per dag
        - 1x per week
        - Heel soms
    validations:
      required: true
  - type: dropdown
    id: impact
    attributes:
      description: "Is hier een impact mee?"
      label: "Wat is de impact van deze bug?"
      options:
        - Hoog
        - Laag
        - Niet
  - type: dropdown
    id: logs
    attributes:
       description: "Is er spoed?"
       label: "Moet er zo snel mogelijk een developer naar kijken?"
       options:
        - Ja
        - Nee
  - type: textarea
    id: logs
    attributes:
      label: Log bestanden
      description: |
       Zet hier eventuele errors in, die gekopieerd zijn uit je F8?
      placeholder: Sleep hier je logbestanden heen
      required: true
  - type: checkboxes
    id: richtlijnen
     attributes:
      label: "Richtlijnen"
      description: "Indien je deze bug meld ga je automatisch akkoord met de richtlijnen. Je dient je ten alle tijden te houden aan deze richtlijnen."
      options:
        - label: Ik ga akkoord met deze richtlijnen.
          required: true
